version: '3.8'
services:
  jobmanager:
    image: flink:1.14.3-scala_2.12-java11
    container_name: jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./flink/data/:/flink-data/
    networks:
      - net-flink
  taskmanager1:
    image: flink:1.14.3-scala_2.12-java11
    container_name: taskmanager1
    expose:
      - "6121"
      - "6122"
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    depends_on:
      - jobmanager
    networks:
      - net-flink
  taskmanager2:
    image: flink:1.14.3-scala_2.12-java11
    container_name: taskmanager2
    expose:
      - "6121"
      - "6122"
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    depends_on:
      - jobmanager
    networks:
      - net-flink
networks:
  net-flink:
    driver: bridge