version: '3.7'
services:
  kafka:
    image: martindai/kafka:3.3.1
    container_name: kafka
    volumes:
      ## 挂载位置（kafka镜像和宿主机器之间时间保持一致）
      - /etc/localtime:/etc/localtime
      - ./kafka/conf/server.properties:/home/kafka/config/kraft/server.properties
      - ./kafka/data:/home/kafka/data
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - net-kafka
networks:
  net-kafka:
    driver: bridge